version: "3.9"
services:
  elasticsearch:
    image: "elasticsearch:7.17.0"
    networks:
      - elk_net
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - "discovery.type=single-node"
    volumes:
      - elastic_data:/usr/share/elasticsearch/data
  kibana:
    image: "kibana:7.17.0"
    networks:
      - elk_net
    ports:
      - "5601:5601"
networks:
  elk_net:
volumes:
  elastic_data:
