version: "3.8"
services:
  elasticsearch:
    image: "elasticsearch:8.4.3"
    networks:
      - elk_net
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - "discovery.type=single-node"
      - "xpack.security.enabled=false"
    volumes:
      - elastic_data:/usr/share/elasticsearch/data
  kibana:
    image: "kibana:8.4.3"
    networks:
      - elk_net
    ports:
      - "5601:5601"
networks:
  elk_net:
volumes:
  elastic_data:
